name: CI

on:
  push:
#Branch que ir치 executar a action
    branches: [ master ]


  workflow_dispatch:

jobs:
  build:
#Inst칙ncia criada na amazon s3
    runs-on: ubuntu-latest

    steps:
#Pega o c칩digo mais atual do github
#https://github.com/actions
      - uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
# https://github.com/appleboy/scp-action
#Ir치 copiar arquivos via ssh
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }} 
          source: "., !node_modules"
          target: "~/app/igniteChapter2"
